#!/usr/bin/env python3
"""
Script para gerar resources/module-paths.md
Escaneia Docs/life-2/ e mapeia M1-M6 para seus arquivos de schema e diagrams
"""

import os
import json
from pathlib import Path
from typing import Dict, List

def find_module_files(project_root: str) -> Dict[str, Dict[str, List[str]]]:
    """
    Escaneia Docs/life-2/ e retorna mapping:
    {
        "M1": {
            "schema": ["path/to/schema.yaml"],
            "sequence": ["path/to/sequence.md"],
            "flow": ["path/to/flow1.md", "path/to/flow2.md"],
            "class": ["path/to/class-diagrams/m1-auth-profile"]
        },
        ...
    }
    """
    docs_base = Path(project_root) / "Docs" / "life-2"
    mapping = {}

    # Modules to process
    modules = {
        "M1": ("m1", "auth"),
        "M2": ("m2", "content"),
        "M3": ("m3", "discovery"),
        "M4": ("m4", "engagement"),
        "M5": ("m5", "bookmarking"),
        "M6": ("m6", "notifications"),
    }

    # Process each module
    for module_name, (prefix, keyword) in modules.items():
        mapping[module_name] = {
            "schema": [],
            "sequence": [],
            "flow": [],
            "class": [],
            "activity": []
        }

        # Find schema files
        schema_dir = docs_base / "database" / "schema-design"
        if schema_dir.exists():
            for schema_file in schema_dir.glob(f"{prefix}-*-schema.yaml"):
                rel_path = f"Docs/life-2/database/schema-design/{schema_file.name}"
                mapping[module_name]["schema"].append(rel_path)

        # Find sequence diagrams
        seq_dir = docs_base / "diagrams" / "sequence-diagrams"
        if seq_dir.exists():
            for seq_file in seq_dir.glob(f"detailed-{prefix}-*.md"):
                rel_path = f"Docs/life-2/diagrams/sequence-diagrams/{seq_file.name}"
                mapping[module_name]["sequence"].append(rel_path)

        # Find flow diagrams (heuristic: files that match module keywords)
        flow_dir = docs_base / "diagrams" / "flow"
        if flow_dir.exists():
            for flow_file in flow_dir.glob("flow-*.md"):
                # Check if filename contains module keyword (e.g., "login" for M1, "post" for M2)
                filename = flow_file.stem.lower()
                if keyword in filename or prefix in filename:
                    rel_path = f"Docs/life-2/diagrams/flow/{flow_file.name}"
                    mapping[module_name]["flow"].append(rel_path)

        # Find class diagrams
        class_dir = docs_base / "diagrams" / "class-diagrams"
        if class_dir.exists():
            for class_subdir in class_dir.glob(f"{prefix}-*"):
                if class_subdir.is_dir():
                    rel_path = f"Docs/life-2/diagrams/class-diagrams/{class_subdir.name}"
                    mapping[module_name]["class"].append(rel_path)

            # Also check for class-diagram.md
            class_md = class_dir / "class-diagram.md"
            if class_md.exists():
                rel_path = "Docs/life-2/diagrams/class-diagrams/class-diagram.md"
                if rel_path not in mapping[module_name]["class"]:
                    # Store as reference for all modules
                    pass

        # Find activity diagrams
        activity_dir = docs_base / "diagrams" / "activity-diagrams"
        if activity_dir.exists():
            for activity_file in activity_dir.glob(f"*{prefix}*.md"):
                rel_path = f"Docs/life-2/diagrams/activity-diagrams/{activity_file.name}"
                mapping[module_name]["activity"].append(rel_path)

    return mapping

def generate_markdown(mapping: Dict) -> str:
    """
    Gera conteúdo Markdown para resources/module-paths.md
    """
    md = """# Module-to-File Path Mapping

> Auto-generated by `scripts/generate-module-paths.py`
> Data: Mapping giữa các modules (M1-M6) và file paths thực tế trong Docs/life-2/

---

"""

    for module_name in sorted(mapping.keys()):
        files = mapping[module_name]
        md += f"## {module_name}\n\n"

        md += "### Schema\n```\n"
        for schema in files["schema"]:
            md += f"  {schema}\n"
        md += "```\n\n"

        md += "### Sequence Diagram\n```\n"
        for seq in files["sequence"]:
            md += f"  {seq}\n"
        md += "```\n\n"

        md += "### Flow Diagrams\n```\n"
        if files["flow"]:
            for flow in files["flow"]:
                md += f"  {flow}\n"
        else:
            md += "  (none found)\n"
        md += "```\n\n"

        md += "### Class Diagram\n```\n"
        if files["class"]:
            for cls in files["class"]:
                md += f"  {cls}\n"
        else:
            md += "  Docs/life-2/diagrams/class-diagrams/class-diagram.md\n"
        md += "```\n\n"

        md += "### Activity Diagram\n```\n"
        if files["activity"]:
            for act in files["activity"]:
                md += f"  {act}\n"
        else:
            md += "  (see Docs/life-2/diagrams/activity-diagrams/)\n"
        md += "```\n\n"

    md += "---\n\n## JSON Format (cho resource_scanner.py)\n\n```json\n"
    md += json.dumps(mapping, indent=2, ensure_ascii=False)
    md += "\n```\n"

    return md

def main():
    # Find project root (should be run from project root or .skill-context dir)
    script_dir = Path(__file__).parent.parent.parent.parent  # Navigate up to project root
    if not (script_dir / "Docs" / "life-2").exists():
        # Try current directory
        script_dir = Path.cwd()

    print(f"📁 Project root: {script_dir}")
    print(f"🔍 Scanning Docs/life-2/...")

    # Generate mapping
    mapping = find_module_files(str(script_dir))

    # Generate markdown
    markdown_content = generate_markdown(mapping)

    # Output to file
    output_path = script_dir / ".skill-context" / "ui-architecture-analyst" / "resources" / "module-paths.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)

    print(f"✅ Generated: {output_path}")
    print(f"\n📊 Summary:")
    for module, files in mapping.items():
        print(f"  {module}: {len(files['schema'])} schema, "
              f"{len(files['sequence'])} seq, {len(files['flow'])} flow, "
              f"{len(files['class'])} class, {len(files['activity'])} activity")

    # Also output JSON to stdout
    print("\n📄 JSON Output:")
    print(json.dumps(mapping, indent=2, ensure_ascii=False))

if __name__ == "__main__":
    main()
